### ISSUE TITLE
what I need to do next and how to use the Lambda package?

### ISSUE THREAD

**Issue by yssummer** [awslabs/serverless-bot-framework#2]
I have executed the './build-s3-dist.sh bucket-base-name v1.0' command successfully and the Lambda package is also built successfully on my server. But I still don't know what I need to do next and how to use the Lambda package. Besides, after executing the command, there isn't anything in my bucket. Thanks.

**Comment by thomasphorton** [comment]
The script you ran builds the Lambda zips, but doesn't deploy them to S3, so you'll have to do that yourself.

Once you've done that, you'll have to edit the CloudFormation templates to reference your code instead of what we host. Take a look at [this section](https://github.com/awslabs/serverless-bot-framework/blob/master/deployment/serverless-bot-framework.template#L173)). You'll need to go through each of the templates and replace the S3Bucket and S3Key of each of the Lambda functions.

Once you do that, you should be able to upload the template to CloudFormation and have everything run using your code.

Let me know if you have any other problems!

**Comment by thomasphorton** [comment]
I should also mention- you only need to do this if you're customizing the code. If you'd just like to run the solution, you can find pre-built CloudFormation templates and a ton of documentation on our [AWS Serverless Bot Framework Documentation](https://docs.aws.amazon.com/solutions/latest/serverless-bot-framework/deployment.html) page!

**Comment by yssummer** [comment]
Dear Tom Horton,
Thanks a lot for your instructions. I have successfully deployed the project.


Best Regards,
Yishuang Ning








At 2018-09-26 05:34:46, "Tom Horton" <notifications@github.com> wrote:


The script you ran builds the Lambda zips, but doesn't deploy them to S3, so you'll have to do that yourself.

Once you've done that, you'll have to edit the CloudFormation templates to reference your code instead of what we host. Take a look at this section). You'll need to go through each of the templates and replace the S3Bucket and S3Key of each of the Lambda functions.

Once you do that, you should be able to upload the template to CloudFormation and have everything run using your code.

Let me know if you have any other problems!

**Comment by yssummer** [comment]
Thanks. I have deployed the project successfully.


Best Regards,
Yishuang Ning





At 2018-09-26 05:37:47, "Tom Horton" <notifications@github.com> wrote:


I should also mention- you only need to do this if you're customizing the code. If you'd just like to run the solution, you can find pre-built CloudFormation templates and a ton of documentation on our AWS Serverless Bot Framework Documentation page!
